[package]
name = "promptpunch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
log = "0.4.22"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = "1.41.1"
